name: grocery_app
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.0
  equatable: ^2.0.5  # Added for value-based equality in entities
  socket_io_client: ^2.0.3  # Real-time Socket.IO client

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  Custom lint plugin (your own rule package)
  naming_conventions_lint:
    path: ../naming_conventions_lint

  #  Lint & Analysis tools
  custom_lint: ^0.6.4
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/svgs/nav_bar/
    - assets/svgs/category_screen/
