name: grocery_app
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  Custom lint plugin (your own rule package)
  naming_conventions_lint:
    path: ../naming_conventions_lint

  #  Lint & Analysis tools
  custom_lint: ^0.6.4
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
