name: grocery_app
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^17.0.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  fpdart: ^1.2.0
  riverpod_annotation: ^2.5.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  Custom lint plugin (your own rule package)
  naming_conventions_lint:
    path: ../naming_conventions_lint

  #  Lint & Analysis tools

  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  build_runner: ^2.4.10
  custom_lint: ^0.7.4
  riverpod_generator: ^2.5.1
  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
