// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:grocery_app/core/storage/hive/adapters/address.dart';
import 'package:grocery_app/core/storage/hive/adapters/delivery_tracking.dart';
import 'package:grocery_app/core/storage/hive/adapters/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(DeliveryTrackingDataAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(DeliveryTrackingDataAdapter());
    registerAdapter(UserModelAdapter());
  }
}
